/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InformationDeskRouteImport } from './routes/information-desk'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as VeterinarianProfileRouteImport } from './routes/veterinarian-profile'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as ApiAnalyzeGuestMediaRouteImport } from './routes/api/analyze-guest-media'
import { Route as ApiAnalyzeMediaRouteImport } from './routes/api/analyze-media'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat/$threadId'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinBusinessRouteImport } from './routes/join.business'
import { Route as JoinOwnerRouteImport } from './routes/join.owner'
import { Route as JoinVeterinarianRouteImport } from './routes/join.veterinarian'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceAppointmentsRouteImport } from './routes/workspace/appointments'
import { Route as WorkspaceClinicSetupRouteImport } from './routes/workspace/clinic-setup'
import { Route as WorkspaceLocationsRouteImport } from './routes/workspace/locations'
import { Route as WorkspacePatientsRouteImport } from './routes/workspace/patients'
import { Route as WorkspaceVeterinariansRouteImport } from './routes/workspace/veterinarians'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationDeskRoute = InformationDeskRouteImport.update({
  id: '/information-desk',
  path: '/information-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const VeterinarianProfileRoute = VeterinarianProfileRouteImport.update({
  id: '/veterinarian-profile',
  path: '/veterinarian-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeGuestMediaRoute = ApiAnalyzeGuestMediaRouteImport.update({
  id: '/api/analyze-guest-media',
  path: '/api/analyze-guest-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeMediaRoute = ApiAnalyzeMediaRouteImport.update({
  id: '/api/analyze-media',
  path: '/api/analyze-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinBusinessRoute = JoinBusinessRouteImport.update({
  id: '/join/business',
  path: '/join/business',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinOwnerRoute = JoinOwnerRouteImport.update({
  id: '/join/owner',
  path: '/join/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinVeterinarianRoute = JoinVeterinarianRouteImport.update({
  id: '/join/veterinarian',
  path: '/join/veterinarian',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAppointmentsRoute = WorkspaceAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceClinicSetupRoute = WorkspaceClinicSetupRouteImport.update({
  id: '/clinic-setup',
  path: '/clinic-setup',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceLocationsRoute = WorkspaceLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePatientsRoute = WorkspacePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceVeterinariansRoute = WorkspaceVeterinariansRouteImport.update({
  id: '/veterinarians',
  path: '/veterinarians',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/home': typeof HomeRoute
  '/information-desk': typeof InformationDeskRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/ratings': typeof RatingsRoute
  '/review': typeof ReviewRoute
  '/veterinarian-profile': typeof VeterinarianProfileRoute
  '/api/analyze-guest-media': typeof ApiAnalyzeGuestMediaRoute
  '/api/analyze-media': typeof ApiAnalyzeMediaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/join/business': typeof JoinBusinessRoute
  '/join/owner': typeof JoinOwnerRoute
  '/join/veterinarian': typeof JoinVeterinarianRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/clinic-setup': typeof WorkspaceClinicSetupRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/chat/': typeof ChatIndexRoute
  '/join/': typeof JoinIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/information-desk': typeof InformationDeskRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/ratings': typeof RatingsRoute
  '/review': typeof ReviewRoute
  '/veterinarian-profile': typeof VeterinarianProfileRoute
  '/api/analyze-guest-media': typeof ApiAnalyzeGuestMediaRoute
  '/api/analyze-media': typeof ApiAnalyzeMediaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/join/business': typeof JoinBusinessRoute
  '/join/owner': typeof JoinOwnerRoute
  '/join/veterinarian': typeof JoinVeterinarianRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/clinic-setup': typeof WorkspaceClinicSetupRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/chat': typeof ChatIndexRoute
  '/join': typeof JoinIndexRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/home': typeof HomeRoute
  '/information-desk': typeof InformationDeskRoute
  '/owner': typeof OwnerRoute
  '/payment': typeof PaymentRoute
  '/ratings': typeof RatingsRoute
  '/review': typeof ReviewRoute
  '/veterinarian-profile': typeof VeterinarianProfileRoute
  '/api/analyze-guest-media': typeof ApiAnalyzeGuestMediaRoute
  '/api/analyze-media': typeof ApiAnalyzeMediaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/join/business': typeof JoinBusinessRoute
  '/join/owner': typeof JoinOwnerRoute
  '/join/veterinarian': typeof JoinVeterinarianRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/clinic-setup': typeof WorkspaceClinicSetupRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/chat/': typeof ChatIndexRoute
  '/join/': typeof JoinIndexRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/account'
    | '/auth'
    | '/chat'
    | '/home'
    | '/information-desk'
    | '/owner'
    | '/payment'
    | '/ratings'
    | '/review'
    | '/veterinarian-profile'
    | '/api/analyze-guest-media'
    | '/api/analyze-media'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/chat/$threadId'
    | '/join/business'
    | '/join/owner'
    | '/join/veterinarian'
    | '/workspace/appointments'
    | '/workspace/clinic-setup'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/veterinarians'
    | '/chat/'
    | '/join/'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/home'
    | '/information-desk'
    | '/owner'
    | '/payment'
    | '/ratings'
    | '/review'
    | '/veterinarian-profile'
    | '/api/analyze-guest-media'
    | '/api/analyze-media'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/chat/$threadId'
    | '/join/business'
    | '/join/owner'
    | '/join/veterinarian'
    | '/workspace/appointments'
    | '/workspace/clinic-setup'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/veterinarians'
    | '/chat'
    | '/join'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/account'
    | '/auth'
    | '/chat'
    | '/home'
    | '/information-desk'
    | '/owner'
    | '/payment'
    | '/ratings'
    | '/review'
    | '/veterinarian-profile'
    | '/api/analyze-guest-media'
    | '/api/analyze-media'
    | '/api/chat'
    | '/api/transcribe'
    | '/api/tts'
    | '/chat/$threadId'
    | '/join/business'
    | '/join/owner'
    | '/join/veterinarian'
    | '/workspace/appointments'
    | '/workspace/clinic-setup'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/veterinarians'
    | '/chat/'
    | '/join/'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  HomeRoute: typeof HomeRoute
  InformationDeskRoute: typeof InformationDeskRoute
  OwnerRoute: typeof OwnerRoute
  PaymentRoute: typeof PaymentRoute
  RatingsRoute: typeof RatingsRoute
  ReviewRoute: typeof ReviewRoute
  VeterinarianProfileRoute: typeof VeterinarianProfileRoute
  ApiAnalyzeGuestMediaRoute: typeof ApiAnalyzeGuestMediaRoute
  ApiAnalyzeMediaRoute: typeof ApiAnalyzeMediaRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  JoinBusinessRoute: typeof JoinBusinessRoute
  JoinOwnerRoute: typeof JoinOwnerRoute
  JoinVeterinarianRoute: typeof JoinVeterinarianRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information-desk': {
      id: '/information-desk'
      path: '/information-desk'
      fullPath: '/information-desk'
      preLoaderRoute: typeof InformationDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veterinarian-profile': {
      id: '/veterinarian-profile'
      path: '/veterinarian-profile'
      fullPath: '/veterinarian-profile'
      preLoaderRoute: typeof VeterinarianProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-guest-media': {
      id: '/api/analyze-guest-media'
      path: '/api/analyze-guest-media'
      fullPath: '/api/analyze-guest-media'
      preLoaderRoute: typeof ApiAnalyzeGuestMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-media': {
      id: '/api/analyze-media'
      path: '/api/analyze-media'
      fullPath: '/api/analyze-media'
      preLoaderRoute: typeof ApiAnalyzeMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/business': {
      id: '/join/business'
      path: '/join/business'
      fullPath: '/join/business'
      preLoaderRoute: typeof JoinBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/owner': {
      id: '/join/owner'
      path: '/join/owner'
      fullPath: '/join/owner'
      preLoaderRoute: typeof JoinOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/veterinarian': {
      id: '/join/veterinarian'
      path: '/join/veterinarian'
      fullPath: '/join/veterinarian'
      preLoaderRoute: typeof JoinVeterinarianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/appointments': {
      id: '/workspace/appointments'
      path: '/appointments'
      fullPath: '/workspace/appointments'
      preLoaderRoute: typeof WorkspaceAppointmentsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/clinic-setup': {
      id: '/workspace/clinic-setup'
      path: '/clinic-setup'
      fullPath: '/workspace/clinic-setup'
      preLoaderRoute: typeof WorkspaceClinicSetupRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/locations': {
      id: '/workspace/locations'
      path: '/locations'
      fullPath: '/workspace/locations'
      preLoaderRoute: typeof WorkspaceLocationsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/patients': {
      id: '/workspace/patients'
      path: '/patients'
      fullPath: '/workspace/patients'
      preLoaderRoute: typeof WorkspacePatientsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/veterinarians': {
      id: '/workspace/veterinarians'
      path: '/veterinarians'
      fullPath: '/workspace/veterinarians'
      preLoaderRoute: typeof WorkspaceVeterinariansRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceAppointmentsRoute: typeof WorkspaceAppointmentsRoute
  WorkspaceClinicSetupRoute: typeof WorkspaceClinicSetupRoute
  WorkspaceLocationsRoute: typeof WorkspaceLocationsRoute
  WorkspacePatientsRoute: typeof WorkspacePatientsRoute
  WorkspaceVeterinariansRoute: typeof WorkspaceVeterinariansRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAppointmentsRoute: WorkspaceAppointmentsRoute,
  WorkspaceClinicSetupRoute: WorkspaceClinicSetupRoute,
  WorkspaceLocationsRoute: WorkspaceLocationsRoute,
  WorkspacePatientsRoute: WorkspacePatientsRoute,
  WorkspaceVeterinariansRoute: WorkspaceVeterinariansRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  HomeRoute: HomeRoute,
  InformationDeskRoute: InformationDeskRoute,
  OwnerRoute: OwnerRoute,
  PaymentRoute: PaymentRoute,
  RatingsRoute: RatingsRoute,
  ReviewRoute: ReviewRoute,
  VeterinarianProfileRoute: VeterinarianProfileRoute,
  ApiAnalyzeGuestMediaRoute: ApiAnalyzeGuestMediaRoute,
  ApiAnalyzeMediaRoute: ApiAnalyzeMediaRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  JoinBusinessRoute: JoinBusinessRoute,
  JoinOwnerRoute: JoinOwnerRoute,
  JoinVeterinarianRoute: JoinVeterinarianRoute,
  JoinIndexRoute: JoinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
