/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceAnalyticsRouteImport } from './routes/workspace/analytics'
import { Route as WorkspaceAppointmentsRouteImport } from './routes/workspace/appointments'
import { Route as WorkspaceLocationsRouteImport } from './routes/workspace/locations'
import { Route as WorkspacePatientsRouteImport } from './routes/workspace/patients'
import { Route as WorkspaceServicesRouteImport } from './routes/workspace/services'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace/settings'
import { Route as WorkspaceVeterinariansRouteImport } from './routes/workspace/veterinarians'
import { Route as WorkspaceIntakesIndexRouteImport } from './routes/workspace/intakes/index'
import { Route as WorkspaceIntakesIntakeIdRouteImport } from './routes/workspace/intakes/$intakeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAnalyticsRoute = WorkspaceAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceAppointmentsRoute = WorkspaceAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceLocationsRoute = WorkspaceLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspacePatientsRoute = WorkspacePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceServicesRoute = WorkspaceServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceVeterinariansRoute = WorkspaceVeterinariansRouteImport.update({
  id: '/veterinarians',
  path: '/veterinarians',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIntakesIndexRoute = WorkspaceIntakesIndexRouteImport.update({
  id: '/intakes/',
  path: '/intakes/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIntakesIntakeIdRoute =
  WorkspaceIntakesIntakeIdRouteImport.update({
    id: '/intakes/$intakeId',
    path: '/intakes/$intakeId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/services': typeof WorkspaceServicesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes/': typeof WorkspaceIntakesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/services': typeof WorkspaceServicesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes': typeof WorkspaceIntakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/workspace/analytics': typeof WorkspaceAnalyticsRoute
  '/workspace/appointments': typeof WorkspaceAppointmentsRoute
  '/workspace/locations': typeof WorkspaceLocationsRoute
  '/workspace/patients': typeof WorkspacePatientsRoute
  '/workspace/services': typeof WorkspaceServicesRoute
  '/workspace/settings': typeof WorkspaceSettingsRoute
  '/workspace/veterinarians': typeof WorkspaceVeterinariansRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes/': typeof WorkspaceIntakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/workspace/analytics'
    | '/workspace/appointments'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/services'
    | '/workspace/settings'
    | '/workspace/veterinarians'
    | '/workspace/'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workspace/analytics'
    | '/workspace/appointments'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/services'
    | '/workspace/settings'
    | '/workspace/veterinarians'
    | '/workspace'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/workspace/analytics'
    | '/workspace/appointments'
    | '/workspace/locations'
    | '/workspace/patients'
    | '/workspace/services'
    | '/workspace/settings'
    | '/workspace/veterinarians'
    | '/workspace/'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/analytics': {
      id: '/workspace/analytics'
      path: '/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof WorkspaceAnalyticsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/appointments': {
      id: '/workspace/appointments'
      path: '/appointments'
      fullPath: '/workspace/appointments'
      preLoaderRoute: typeof WorkspaceAppointmentsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/locations': {
      id: '/workspace/locations'
      path: '/locations'
      fullPath: '/workspace/locations'
      preLoaderRoute: typeof WorkspaceLocationsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/patients': {
      id: '/workspace/patients'
      path: '/patients'
      fullPath: '/workspace/patients'
      preLoaderRoute: typeof WorkspacePatientsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/services': {
      id: '/workspace/services'
      path: '/services'
      fullPath: '/workspace/services'
      preLoaderRoute: typeof WorkspaceServicesRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/settings': {
      id: '/workspace/settings'
      path: '/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/veterinarians': {
      id: '/workspace/veterinarians'
      path: '/veterinarians'
      fullPath: '/workspace/veterinarians'
      preLoaderRoute: typeof WorkspaceVeterinariansRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/intakes/': {
      id: '/workspace/intakes/'
      path: '/intakes'
      fullPath: '/workspace/intakes/'
      preLoaderRoute: typeof WorkspaceIntakesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/intakes/$intakeId': {
      id: '/workspace/intakes/$intakeId'
      path: '/intakes/$intakeId'
      fullPath: '/workspace/intakes/$intakeId'
      preLoaderRoute: typeof WorkspaceIntakesIntakeIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceAnalyticsRoute: typeof WorkspaceAnalyticsRoute
  WorkspaceAppointmentsRoute: typeof WorkspaceAppointmentsRoute
  WorkspaceLocationsRoute: typeof WorkspaceLocationsRoute
  WorkspacePatientsRoute: typeof WorkspacePatientsRoute
  WorkspaceServicesRoute: typeof WorkspaceServicesRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceVeterinariansRoute: typeof WorkspaceVeterinariansRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceIntakesIntakeIdRoute: typeof WorkspaceIntakesIntakeIdRoute
  WorkspaceIntakesIndexRoute: typeof WorkspaceIntakesIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceAnalyticsRoute: WorkspaceAnalyticsRoute,
  WorkspaceAppointmentsRoute: WorkspaceAppointmentsRoute,
  WorkspaceLocationsRoute: WorkspaceLocationsRoute,
  WorkspacePatientsRoute: WorkspacePatientsRoute,
  WorkspaceServicesRoute: WorkspaceServicesRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceVeterinariansRoute: WorkspaceVeterinariansRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceIntakesIntakeIdRoute: WorkspaceIntakesIntakeIdRoute,
  WorkspaceIntakesIndexRoute: WorkspaceIntakesIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
