/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForPetOwnersRouteImport } from './routes/for-pet-owners'
import { Route as ForVeterinaryTeamsRouteImport } from './routes/for-veterinary-teams'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as MyPetsRouteImport } from './routes/my-pets'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as WorkspaceRouteRouteImport } from './routes/workspace/route'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace/index'
import { Route as WorkspaceIntakesIndexRouteImport } from './routes/workspace/intakes/index'
import { Route as WorkspaceIntakesIntakeIdRouteImport } from './routes/workspace/intakes/$intakeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPetOwnersRoute = ForPetOwnersRouteImport.update({
  id: '/for-pet-owners',
  path: '/for-pet-owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVeterinaryTeamsRoute = ForVeterinaryTeamsRouteImport.update({
  id: '/for-veterinary-teams',
  path: '/for-veterinary-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPetsRoute = MyPetsRouteImport.update({
  id: '/my-pets',
  path: '/my-pets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRouteRoute = WorkspaceRouteRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIntakesIndexRoute = WorkspaceIntakesIndexRouteImport.update({
  id: '/intakes/',
  path: '/intakes/',
  getParentRoute: () => WorkspaceRouteRoute,
} as any)
const WorkspaceIntakesIntakeIdRoute =
  WorkspaceIntakesIntakeIdRouteImport.update({
    id: '/intakes/$intakeId',
    path: '/intakes/$intakeId',
    getParentRoute: () => WorkspaceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/for-pet-owners': typeof ForPetOwnersRoute
  '/for-veterinary-teams': typeof ForVeterinaryTeamsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/my-pets': typeof MyPetsRoute
  '/platform': typeof PlatformRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes/': typeof WorkspaceIntakesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-pet-owners': typeof ForPetOwnersRoute
  '/for-veterinary-teams': typeof ForVeterinaryTeamsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/my-pets': typeof MyPetsRoute
  '/platform': typeof PlatformRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes': typeof WorkspaceIntakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRouteRouteWithChildren
  '/for-pet-owners': typeof ForPetOwnersRoute
  '/for-veterinary-teams': typeof ForVeterinaryTeamsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/intake': typeof IntakeRoute
  '/my-pets': typeof MyPetsRoute
  '/platform': typeof PlatformRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/workspace/intakes/$intakeId': typeof WorkspaceIntakesIntakeIdRoute
  '/workspace/intakes/': typeof WorkspaceIntakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace'
    | '/for-pet-owners'
    | '/for-veterinary-teams'
    | '/how-it-works'
    | '/intake'
    | '/my-pets'
    | '/platform'
    | '/workspace/'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-pet-owners'
    | '/for-veterinary-teams'
    | '/how-it-works'
    | '/intake'
    | '/my-pets'
    | '/platform'
    | '/workspace'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes'
  id:
    | '__root__'
    | '/'
    | '/workspace'
    | '/for-pet-owners'
    | '/for-veterinary-teams'
    | '/how-it-works'
    | '/intake'
    | '/my-pets'
    | '/platform'
    | '/workspace/'
    | '/workspace/intakes/$intakeId'
    | '/workspace/intakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRouteRoute: typeof WorkspaceRouteRouteWithChildren
  ForPetOwnersRoute: typeof ForPetOwnersRoute
  ForVeterinaryTeamsRoute: typeof ForVeterinaryTeamsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IntakeRoute: typeof IntakeRoute
  MyPetsRoute: typeof MyPetsRoute
  PlatformRoute: typeof PlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-pet-owners': {
      id: '/for-pet-owners'
      path: '/for-pet-owners'
      fullPath: '/for-pet-owners'
      preLoaderRoute: typeof ForPetOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-veterinary-teams': {
      id: '/for-veterinary-teams'
      path: '/for-veterinary-teams'
      fullPath: '/for-veterinary-teams'
      preLoaderRoute: typeof ForVeterinaryTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-pets': {
      id: '/my-pets'
      path: '/my-pets'
      fullPath: '/my-pets'
      preLoaderRoute: typeof MyPetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/intakes/': {
      id: '/workspace/intakes/'
      path: '/intakes'
      fullPath: '/workspace/intakes/'
      preLoaderRoute: typeof WorkspaceIntakesIndexRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
    '/workspace/intakes/$intakeId': {
      id: '/workspace/intakes/$intakeId'
      path: '/intakes/$intakeId'
      fullPath: '/workspace/intakes/$intakeId'
      preLoaderRoute: typeof WorkspaceIntakesIntakeIdRouteImport
      parentRoute: typeof WorkspaceRouteRoute
    }
  }
}

interface WorkspaceRouteRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceIntakesIntakeIdRoute: typeof WorkspaceIntakesIntakeIdRoute
  WorkspaceIntakesIndexRoute: typeof WorkspaceIntakesIndexRoute
}

const WorkspaceRouteRouteChildren: WorkspaceRouteRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceIntakesIntakeIdRoute: WorkspaceIntakesIntakeIdRoute,
  WorkspaceIntakesIndexRoute: WorkspaceIntakesIndexRoute,
}

const WorkspaceRouteRouteWithChildren = WorkspaceRouteRoute._addFileChildren(
  WorkspaceRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRouteRoute: WorkspaceRouteRouteWithChildren,
  ForPetOwnersRoute: ForPetOwnersRoute,
  ForVeterinaryTeamsRoute: ForVeterinaryTeamsRoute,
  HowItWorksRoute: HowItWorksRoute,
  IntakeRoute: IntakeRoute,
  MyPetsRoute: MyPetsRoute,
  PlatformRoute: PlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
